#!/bin/bash

SRCDIR=/work/scratch-pw2/pmcguire/TRENDYv12/sdgvm/tools
ARGS="nsites<-15789 grids<-32 cores<-8 fd<-'${SRCDIR}' dir<-'/work/scratch-pw2/pmcguire/sdgvmR' wd<-'/work/scratch-pw2/pmcguire/sdgvmR/TRENDYv12_v2' sim<-'S3' outputdir<-'output/' email<-'mcguirepatr@gmail.com'" 
PARG="person<-'Patrick C. McGuire'" 
IARG="institution<-'University of Reading'" 
TIMEARGS="ny<-323 sty<-1700"
TIMEARGSMON="ny<-123 sty<-1900"


cd $SRCDIR
# stich gridded output together
ALLARGS="${ARGS} ${TIMEARGS} monthly<-F daily<-F netcdf<-F"
Rscript postprocess_mp.R ${ALLARGS}

# generate netcdf output
ALLARGS="${ARGS} ${TIMEARGS} stich<-F netcdf<-T monthly<-F daily<-F"
Rscript postprocess_mp.R ${ALLARGS} "$PARG" "$IARG"
ALLARGS="${ARGS} ${TIMEARGSMON} stich<-F netcdf<-T monthly<-F daily<-F ncdf_avars<-c('cVegpft','landCoverFrac') "
Rscript postprocess_mp.R ${ALLARGS} "$PARG" "$IARG"
ALLARGS="${ARGS} ${TIMEARGS} outsyear<-1900 stich<-F netcdf<-T monthly<-F daily<-F ncdf_avars<-c('fFire','fLuc')"
Rscript postprocess_mp.R ${ALLARGS} "$PARG" "$IARG"

# stich sub-annual gridded output together - monthly
ALLARGS="${ARGS} ${TIMEARGSMON} netcdf<-F annual<-F daily<-F"
Rscript postprocess_mp.R ${ALLARGS}

# generate sub-annual netcdf output - monthly
ALLARGS="${ARGS} ${TIMEARGSMON} stich<-F netcdf<-T annual<-F daily<-F"
Rscript postprocess_mp.R ${ALLARGS} "$PARG" "$IARG"



### END ###
