#!/bin/bash

# script to run SDGVM in parallel on 30 cores 
# designed to be run from within it's own directory

#HOME=#HOME#
MODEL=#HOME##MOD#
SITES=#HOME##DATA#/sites/global_3p75x2p5deg.dat
INPUT='input_global.dat'
OUTPUT=output

SITE_INDEX=( 0 45 95 135 173 205 236 267 299 330 362 400 449 511 574 635 678 723 773 830 882 962 1020 1082 1154 1252 1315 1384 1449 1520 1631 )


# start script

# clear output directories
rm -r ./$OUTPUT
rm -r ./src

# copy source code and compiled model run file
mkdir ./$OUTPUT
mkdir ./src
cp $MODEL/*.f    ./src
cp $MODEL/sdgvm0 ./src

# run loop 
((e=${#SITE_INDEX[*]} - 1 ))

for s in `seq 1 $e` ;do
((s1=$s - 1))
((s2=${SITE_INDEX[$s1]} + 1))

mkdir ./$OUTPUT/grid$s

echo "./src/sdgvm0 $INPUT ./$OUTPUT/grid$s  $SITES $s2 ${SITE_INDEX[$s]} > ./$OUTPUT/g${s}out.txt &"
./src/sdgvm0 $INPUT ./$OUTPUT/grid$s  $SITES $s2 ${SITE_INDEX[$s]} > ./$OUTPUT/g${s}out.txt &

done

wait
