#!/bin/bash

SRCDIR=/work/scratch-pw2/pmcguire/TRENDYv12/sdgvm/tools
ARGS="nsites<-15789 grids<-32 cores<-8 fd<-'${SRCDIR}' dir<-'/work/scratch-pw2/pmcguire/sdgvmR' wd<-'/work/scratch-pw2/pmcguire/sdgvmR/TRENDYv12_v2' sim<-'spin_accel' outputdir<-'output/'"
TIMEARGS="ny<-500 sty<-1"
TIMEARGSMON="ny<-500"

cd $SRCDIR
# stich annual gridded output together
ALLARGS="${ARGS} ${TIMEARGS} monthly<-F daily<-F netcdf<-F"
Rscript postprocess_mp.R ${ALLARGS}

# stich sub-annual gridded output together - monthly
ALLARGS="${ARGS} ${TIMEARGS} annual<-F daily<-F netcdf<-F"
Rscript postprocess_mp.R ${ALLARGS}



### END ###
