#!/bin/bash

# Sets up an SDGVM runtype, a broad class of simulations that have similar configurations 
# called by setup_SDGVM_project.bs 
# expects SDGVM_RUNTYPE to exist as an environment variable

# to add a new runtype simply add an additional case to the below case statement 

if [ $SDGVM_RUNTYPE == 'TRENDYv7' ]; then

  # For TRENDYv7
  # - and later TRENDY iterations

  # directory where template simulations are to be copied from 
  # - relative to "template" directory in model source code directory 
  SDGVM_CPRUN="master_mp"

  # Spinup 
  SDGVM_SPIN="spin_accelv7"

  # Main simulation ensemble  
  SDGVM_MAIN_SIMS=( S0v7 S1v7 S2v7 S3v7 S4v7 S8v7 )
  

elif [ $SDGVM_RUNTYPE == 'scratch' ]; then

  # for user-defined runtypes

  # Spinup directory 
  SDGVM_SPIN="spin"

  # directory where template simulations are to be copied from, relative to model source code 
  SDGVM_CPRUN=""

  # Main simulation ensemble  
  #MAIN_SIMS=( NC_zen0_beers C_zen0_beers C_zen_beers C_zen0_beersC C_zen_beersC NC_zen0_LP C_zen0_LP C_zen_LP  )
  #MAIN_SIMS=( Walker_N_ModA Walker_N_ModA_Tacc Kattge_ModA Kattge_ModA_Tacc  )
  #MAIN_SIMS=( Constant Constant_ModA Constant_ModA_Tacc LUNA LUNA_ModA LUNA_ModA_Tacc  )
  #MAIN_SIMS=( tpu0 tpu1 tpu2 tpu3  )
  #MAIN_SIMS=( spin_accelv7 S0v7 S1v7 S3v7 spin_accelv7_npslim S0v7_npslim S1v7_npslim S3v7_npslim spin_accelv7_bamort S0v7_bamort S1v7_bamort S3v7_bamort )
  #MAIN_SIMS=( spin_accelv8 spin_shortv8 S0v8 S2p1v8 S2p1_2017_v8 S2p2v8 S2p3v8 )
  #MAIN_SIMS=( spin_accelv8 spin_shortv8 S0v8 S2p1v8 S2p1_2017_v8 S2p2v8 S2p3v8 )
  SDGVM_MAIN_SIMS=( run ) 


else
  SDGVM_SETUP_KILL=TRUE
  export SDGVM_SETUP_KILL
  echo ""
  echo "No runtype: ${SDGVM_RUNTYPE}"
  echo "pick one of: TRENDYv7, scratch" 
  echo " or define your own in: ./runtypes.bs"
  echo "SDGVM project setup ABORTED."
  stop
fi


# export variables
export SDGVM_SPIN 
export SDGVM_MAIN_SIMS
export SDGVM_CPRUN 



### END ###
