#!/bin/bash

# Sets up an SDGVM user 
# called by setup_SDGVM_project.bs 
# expects SDGVM_USER to exist as an environment variable

# to add a new user simply add an additional case to the below case statement 


if [ $SDGVM_USER == 'ORNL_APW' ]; then

  # SDGVM directory - source code, run directories, input data are all subdirs of SDGVM_HOME
  SDGVM_HOME=~/models/SDGVM

  # relative to SDGVM_HOME
  SDGVM_PROJECTS_DIR="/run/"                 # all SDGVM projects are housed in subdirectories of this directory
  SDGVM_DATA="/input_data/"                  # all SDGVM input data should be housed in subdirectories of this directory 
  SDGVM_MOD="/src/sdgvm/"                    # SDGVM source code is found in this directory

  # cluster scheduling variables
  SDGVM_BATCHPROC="sbatch"                   # type of job submission system, copies submission script templates that have this file extension 
  SDGVM_BATCHPROCCOM="sbatch submit.sbatch"  # command to run job submission scripts
  SDGVM_USER_EMAIL="walkerap@ornl.gov"    
  SDGVM_USER_NAME="Anthony P. Walker"    
  SDGVM_USER_INSTITUTION="Oak Ridge National Laboratory"    
  SDGVM_USER_ACCOUNT="ccsi"                  # user account on scheduling system
  SDGVM_USER_QUEUE=""                        # user queue on scheduling system
  SDGVM_USER_PARTITION="batch"               # user partition on scheduling system
  SDGVM_WALLTIME="32:00:00"
  SDGVM_MEMORY="0"
  SDGVM_USER_PARTITION_PP="batch"
  SDGVM_WALLTIME_PP="02:00:00"
  SDGVM_MEMORY_PP="0"
  SDGVM_NODES="1"
  SDGVM_NODES_PP="1"
  SDGVM_NP="32"
  SDGVM_NP_PP="32"
  SDGVM_OUTPUT_DIR=""
  SDGVM_OUTPUT_SIM="./output"
  SDGVM_OUTPUT_SPIN="../#SPIN#/output"
    

elif [ $SDGVM_USER == 'ORNL_Base_APW' ]; then

  # SDGVM directory - source code, run directories, input data are all subdirs of SDGVM_HOME
  SDGVM_HOME=~/models/SDGVM

  # relative to SDGVM_HOME
  SDGVM_PROJECTS_DIR="/run/"                 # all SDGVM projects are housed in subdirectories of this directory
  SDGVM_DATA="/input_data/datasymlink/"      # all SDGVM input data should be housed in subdirectories of this directory 
  SDGVM_MOD="/sdgvm/"                        # SDGVM source code is found in this directory

  # cluster scheduling variables
  SDGVM_BATCHPROC="sbatch"                   # type of job submission system, copies submission script templates that have this file extension 
  SDGVM_BATCHPROCCOM="sbatch submit.sbatch"  # command to run job submission scripts
  SDGVM_USER_EMAIL="walkerap@ornl.gov"    
  SDGVM_USER_NAME="Anthony P. Walker"    
  SDGVM_USER_INSTITUTION="Oak Ridge National Laboratory"    
  SDGVM_USER_ACCOUNT="cli185"                # user account on scheduling system
  SDGVM_USER_QUEUE=""                        # user queue on scheduling system
  SDGVM_USER_PARTITION="batch_ccsi"          # user partition on scheduling system
  SDGVM_WALLTIME="24:00:00"
  SDGVM_MEMORY="0"
  SDGVM_USER_PARTITION_PP="batch_ccsi"
  SDGVM_WALLTIME_PP="02:00:00"
  SDGVM_MEMORY_PP="0"
  SDGVM_NODES="1"
  SDGVM_NODES_PP="1"
  SDGVM_NP="128"
  SDGVM_NP_PP="128"
  SDGVM_OUTPUT_DIR="/gpfs/wolf2/cades/cli185/scratch/alp/#PROJECT#/output"  
  SDGVM_OUTPUT_SIM="$SDGVM_OUTPUT_DIR/#SIM#"
  SDGVM_OUTPUT_SPIN="$SDGVM_OUTPUT_DIR/#SPIN#"

elif [ $SDGVM_USER == 'UR_PCM' ]; then

  # SDGVM directory - source code, run directories, input data are all subdirs of SDGVM_HOME
  SDGVM_HOME="/gws/nopw/j04/nexcs/pmcguire"
  #SDGVM_HOME="/work/scratch-pw3/pmcguire"

  # relative to SDGVM_HOME
  SDGVM_PROJECTS_DIR="/sdgvmR2"
  SDGVM_DATA="/TRENDYv12/db"
  #SDGVM_MOD="/TRENDYv12/sdgvm"
  SDGVM_MOD="/TRENDYv10/sdgvm_v6n_debug" #copy from v10

  # cluster scheduling variables
  SDGVM_BATCHPROC="sbatch"
  SDGVM_BATCHPROCCOM="sbatch submit.sbatch"
  SDGVM_USER_EMAIL="mcguirepatr@gmail.com"
  SDGVM_USER_NAME="Patrick C. McGuire"    
  SDGVM_USER_INSTITUTION="University of Reading"    
  SDGVM_USER_ACCOUNT=""
  SDGVM_USER_QUEUE=""
  SDGVM_USER_PARTITION="par-multi"
  SDGVM_WALLTIME="48:00:00"
  SDGVM_MEMORY="64000"
  SDGVM_NODES="8"
  SDGVM_NP="4"
  SDGVM_USER_PARTITION_PP="par-single"
  SDGVM_WALLTIME_PP="08:00:00"
  SDGVM_MEMORY_PP="64000"
  SDGVM_NODES_PP="1"
  SDGVM_NP_PP="8"
  SDGVM_OUTPUT_DIR=""
  SDGVM_OUTPUT_SIM="./output"
  SDGVM_OUTPUT_SPIN="../#SPIN#/output"

else
  echo ""
  echo "No institute and username tag:"
  echo "  ${SDGVM_USER}"
  echo "pick one of:"
  echo "  ORNL_APW, UR_PCM"
  echo " or define your own in: ../project_config/users.bs."
  echo "SDGVM project setup ABORTED."
  exit 1
fi


# export variables
export SDGVM_HOME 
export SDGVM_PROJECTS_DIR
export SDGVM_DATA 
export SDGVM_MOD 
export SDGVM_BATCHPROC
export SDGVM_BATCHPROCCOM
export SDGVM_USER_EMAIL
export SDGVM_USER_NAME
export SDGVM_USER_INSTITUTION
export SDGVM_USER_ACCOUNT
export SDGVM_USER_QUEUE
export SDGVM_USER_PARTITION
export SDGVM_USER_PARTITION_PP
export SDGVM_WALLTIME
export SDGVM_WALLTIME_PP
export SDGVM_MEMORY
export SDGVM_MEMORY_PP
export SDGVM_NODES
export SDGVM_NODES_PP
export SDGVM_NP
export SDGVM_NP_PP
export SDGVM_OUTPUT_DIR
export SDGVM_OUTPUT_SIM
export SDGVM_OUTPUT_SPIN


### END ###
