#!/bin/csh -f


#===============================================================================

#PBS -N SDGVM_#PROJECT#_archive
#PBS -W group_list=cades-ccsi
#PBS -l nodes=1:ppn=1
#PBS -l walltime=5:00:00
#PBS -r n
#PBS -j oe
#PBS -S /bin/csh -V
#PBS -M walkerap@ornl.gov
#PBS -m ea
#PBS -o #PROJDIR#/tools/logs/${PBS_JOBNAME}.o${PBS_JOBID}

#===============================================================================


cd #PROJDIR#

echo "`date` -- SDGVM nc ZIP HAS STARTED" 
./gzip_ncdf.bs
echo "`date` -- SDGVM nc ZIP HAS FINISHED" 

echo "`date` -- SDGVM ARCHIVE HAS STARTED" 
./archive.bs
echo "`date` -- SDGVM ARCHIVE HAS FINISHED" 



### END ###
