#!/bin/bash

SRCDIR=/gws/nopw/j04/nexcs/pmcguire/TRENDYv13/sdgvm_bugfix_negsoilc/tools
ARGS="nsites<-15759 grids<-100 cores<-8 fd<-'${SRCDIR}' dir<-'/work/scratch-pw2/pmcguire/sdgvmR' wd<-'/work/scratch-pw2/pmcguire/sdgvmR/TRENDYv13_v9e' sim<-'spin_accelFS' outputdir<-'output_v10c/' email<-'p.mcguire@reading.ac.uk' project<-'TRENDYv13(2024)'"
PARG="person<-'Patrick C. McGuire'" 
IARG="institution<-'University of Reading'" 
TIMEARGS="ny<-500 sty<-1"
TIMEARGSMON="ny<-500"


cd $SRCDIR
# stich annual gridded output together
ALLARGS="${ARGS} ${TIMEARGS} monthly<-F daily<-F netcdf<-F"
Rscript postprocess_mp.R ${ALLARGS}

# stich sub-annual gridded output together - monthly
ALLARGS="${ARGS} ${TIMEARGSMON} netcdf<-F annual<-F daily<-F"
Rscript postprocess_mp.R ${ALLARGS}

### END ###
