#!/bin/bash

# APW: hard coding things specific to a given machine is not the goal with these templates, 
#      please add this through ageneric tag in the template that gets specific via project_config/users.bs, setup_SDGVM_project.bs and setup_SDGVM.bs
#      same goes for hard coded things in ARGS list below
#module load jasr

SRCDIR=#HOME##MOD#/tools
ARGS="of<-'#PROJECT#_spin' sim<-c(#S#) styr<-1 endyr<-#SPINNY# yr_mean<-c(#SPINNY#-9,#SPINNY#) project<-'#PROJECT#' date<-'230719spin' dir<-'/work/scratch-pw3/pmcguire' rdir<-'sdgvmR2' edir<-'eval_data' tdir<-'${SRCDIR}'"

echo 'ARGS'
echo $ARGS

cd $SRCDIR
# dynamic variables
ALLARGS="${ARGS} via<-c(2,3,8,15,19,20) pyear<-1"
Rscript plot_maps_lattice.R ${ALLARGS} 

# static land cover
ALLARGS="${ARGS} via<-24:32 cov_fixed<-T"
Rscript plot_maps_lattice.R ${ALLARGS} 


#module unload jasr
### END ###
