#!/bin/bash

SRCDIR=/gws/nopw/j04/nexcs/pmcguire/TRENDYv13/sdgvm_bugfix_negsoilc/tools
ARGS="nsites<-15789 grids<-100 cores<-8 fd<-'${SRCDIR}' dir<-'/work/scratch-pw2/pmcguire/sdgvmR' wd<-'/work/scratch-pw2/pmcguire/sdgvmR/TRENDYv13_v9e' sim<-'S6' outputdir<-'output_v10c/' email<-'p.mcguire@reading.ac.uk' project<-'TRENDYv13(2024)' pftnames<-c('BARE','CITY','C3','C3crop','C4','C4crop','Dc_Bl','Dc_Nl','Ev_Bl','Ev_Nl')"
PARG="person<-'Patrick C. McGuire'" 
IARG="institution<-'University of Reading'" 
TIMEARGS="ny<-324 sty<-1700"
TIMEARGSMON="ny<-324 sty<-1700"


cd $SRCDIR
# stich gridded output together
ALLARGS="${ARGS} ${TIMEARGS} monthly<-F daily<-F netcdf<-F"
Rscript postprocess_mp.R ${ALLARGS}

# generate netcdf output
ALLARGS="${ARGS} ${TIMEARGS} stich<-F netcdf<-T monthly<-F daily<-F"
Rscript postprocess_mp.R ${ALLARGS} "$PARG" "$IARG"
ALLARGS="${ARGS} ${TIMEARGSMON} stich<-F netcdf<-T monthly<-F daily<-F ncdf_avars<-c('cVegpft','landCoverFrac','cYieldpft')"
Rscript postprocess_mp.R ${ALLARGS} "$PARG" "$IARG"
ALLARGS="${ARGS} ${TIMEARGS} outsyear<-1900 stich<-F netcdf<-T monthly<-F daily<-F ncdf_avars<-c('fFire','fLuc')"
Rscript postprocess_mp.R ${ALLARGS} "$PARG" "$IARG"

# stich sub-annual gridded output together - monthly: non-pft
ALLARGS="${ARGS} ${TIMEARGSMON} pft<-F netcdf<-F annual<-F daily<-F"
Rscript postprocess_mp.R ${ALLARGS}

# generate sub-annual netcdf output - monthly: non-pft
#skip tgs for now
ALLARGS="${ARGS} ${TIMEARGSMON} stich<-F netcdf<-T annual<-F daily<-F ncdf_mvars<-c('tas','pr','rsds','mrro','mrso','evapotrans','gpp','ra','npp','rh','nbp','nep','lai','tran','soilr','tci')"
Rscript postprocess_mp.R ${ALLARGS} "$PARG" "$IARG"

# do the monthly pft processing last since that takes the longest
# stich sub-annual gridded output together - monthly: pft
ALLARGS="${ARGS} ${TIMEARGSMON} pft<-T netcdf<-F annual<-F daily<-F"
Rscript postprocess_mp.R ${ALLARGS}

# generate sub-annual netcdf output - monthly: pft
ALLARGS="${ARGS} ${TIMEARGSMON} stich<-F netcdf<-T annual<-F daily<-F ncdf_mvars<-c('evapotranspft','transpft','snow_depthpft','gpppft','npppft','laipft')"
Rscript postprocess_mp.R ${ALLARGS} "$PARG" "$IARG"



### END ###
