#!/bin/bash

# Sets up an SDGVM project composed of multiple related runs of SDGVM

# Arguments:
# $1 - project name (required)
# $2 - HOME directory path relative to root (optional)
# $3 - SUBPROJECT name (optional, but $2 must be specified if a subproject is to be created)

# Currently the names of the various runs are hgard coded in the environment variable SIMS 
#SIMS=( NC_zen0_beers C_zen0_beers C_zen_beers C_zen0_beersC C_zen_beersC NC_zen0_LP C_zen0_LP C_zen_LP  )
#SIMS=( Walker_N_ModA Walker_N_ModA_Tacc Kattge_ModA Kattge_ModA_Tacc  )
#SIMS=( Constant Constant_ModA Constant_ModA_Tacc LUNA LUNA_ModA LUNA_ModA_Tacc  )
SIMS=( spin_accel S0 S1 S2 S3  )

# SDGVM directory - source code, run directories, input data are all subdirs of this dir
HOME=~/models/SDGVM
if [ ! -z $2 ]; then HOME=$2; fi
# relative to HOME, where all SDGVM simulations live
PROJECTS_DIR=/run
PDIR=${HOME}${PROJECTS_DIR}
# directory of specific project
PROJECT=$1


SUBPROJECT=''
if [ ! -z $3 ]; then SUBPROJECT=_$3; fi

# setup project directories
mkdir -p $PDIR/$PROJECT
mkdir -p $PDIR/$PROJECT/tools
mkdir -p $PDIR/$PROJECT/tools/logs

# setup project run script 
cp run_project_template.bs  $PDIR/$PROJECT/run_${PROJECT}${SUBPROJECT}.bs
sed -i "s@#S#@${SIMS[*]}@"  $PDIR/$PROJECT/run_${PROJECT}${SUBPROJECT}.bs

# setup project tools
cp ./project_tools/* $PDIR/$PROJECT/tools
sed -i "s@#PROJECT#@$PROJECT@"          $PDIR/$PROJECT/tools/*bs
sed -i "s@#PROJDIR#@${PDIR}${PROJECT}@" $PDIR/$PROJECT/tools/*bs

# set up runs within project
for s in ${SIMS[*]};do
 echo $s
 ./setup_SDGVM.bs $HOME $PROJECT $s 
done


