#!/bin/bash

# This script is designed to copy a template SDGVM directory into an actual run directory
# must be called from the script 'setup_SDGVM_project.bs' to set up multiple runs within a project
# the script renames the directories specified in the run and submit scripts
# once a run is setup the only file that needs editing is the input file (input*.dat)

# Arguments:
# $1 - run name (required) -- relative to SDGVM_PDIR/SDGVM_PROJECT
RUN=$1


# Run directory to copy files into:
RUNDIR=$SDGVM_PDIR/$SDGVM_PROJECT/$RUN/


# set up run directories
mkdir -p $RUNDIR
mkdir -p $RUNDIR/logs


# copy cleaning file
cp ./project_tools/clean.bs $RUNDIR 


cd ../templates/
# copy template submit scripts 
cp ./submit_scripts/*.${SDGVM_BATCHPROC} $RUNDIR


# copy template run scripts
RUNF=run_SDGVM.bs
#echo "Run file: " $RUNF
cp ./run_scripts/$RUNF                 ${RUNDIR}$DEFTRUN
cp ./run_scripts/run_postprocessing.bs $RUNDIR


# run sites script
#source ./sites/sites_${SDGVM_SITESCORES}.bs 


# select and copy template input and param files
cd ./$SDGVM_CPRUN
DEFTIN=input_global.dat
SPECIN=`ls input* | grep $RUN`
if [ ! -z $SPECIN ]; then 
 INPUT=$SPECIN
else 
 INPUT=$DEFTIN 
fi
echo "Input file: " $INPUT
cp $INPUT  $RUNDIR
cp *param* $RUNDIR


# modify run files
cd ${RUNDIR}
#echo "Sites: ${SDGVM_SITES}"
#echo "Sites on each processor: ${SDGVM_N_SITES[@]}"

# submit script
sed -i "s@#RUNDIR#@$RUNDIR@"                   submit*.${SDGVM_BATCHPROC}
sed -i "s@#PROJECT#@$SDGVM_PROJECT@"           submit*.${SDGVM_BATCHPROC}
sed -i "s@#SIM#@$RUN@"                         submit*.${SDGVM_BATCHPROC}
sed -i "s/#EMAIL#/$SDGVM_USER_EMAIL/"          submit*.${SDGVM_BATCHPROC}
sed -i "s@#ACCOUNT#@$SDGVM_USER_ACCOUNT@"      submit*.${SDGVM_BATCHPROC}
sed -i "s@#QUEUE#@$SDGVM_USER_QUEUE@"          submit*.${SDGVM_BATCHPROC}
sed -i "s@#PARTITION#@$SDGVM_USER_PARTITION@"  submit*.${SDGVM_BATCHPROC}
sed -i "s@#NODES#@$SDGVM_NODES@"               submit*.${SDGVM_BATCHPROC}
sed -i "s@#NP#@$SDGVM_NP@"                     submit*.${SDGVM_BATCHPROC}

# SDGVM run script (called by submit script)
sed -i "s@#SITES#@$SDGVM_SITES@"               run_SDGVM.bs
sed -i "s@#N_SITES#@${SDGVM_N_SITES[*]}@"      run_SDGVM.bs
sed -i "s@#HOME#@$SDGVM_HOME@"                 run_SDGVM.bs
sed -i "s@#MOD#@$SDGVM_MOD@"                   run_SDGVM.bs
sed -i "s@#DATA#@$SDGVM_DATA@"                 run_SDGVM.bs
sed -i "s@#INPUT#@$INPUT@"                     run_SDGVM.bs
sed -i "s@#SPIN#@$SDGVM_SPIN@"                 run_SDGVM.bs

# SDGVM input file (commandline argument to SDGVM in run file, configures model run)
sed -i "s@#DATA#@$SDGVM_DATA@"                 $INPUT
sed -i "s@#HOME#@$SDGVM_HOME@"                 $INPUT

# postprocessing script (called by submit script after completion of SDGVM run file execution)
sed -i "s@#HOME#@$SDGVM_HOME@"                 run_postprocessing.bs
sed -i "s@#MOD#@$SDGVM_MOD@"                   run_postprocessing.bs
sed -i "s@#DIR#@$SDGVM_PDIR@"                  run_postprocessing.bs
sed -i "s@#PDIR#@$SDGVM_PDIR$SDGVM_PROJECT@"   run_postprocessing.bs
sed -i "s@#SIM#@$RUN@"                         run_postprocessing.bs
sed -i "s@#SDGVMUSER#@$SDGVM_USER@"            run_postprocessing.bs
sed -i "s@#TSITES#@$SDGVM_SITES_TOTAL@"        run_postprocessing.bs
sed -i "s@#NP#@$SDGVM_NP@"                     run_postprocessing.bs



### END ### 
