#!/bin/bash

# Sets up an SDGVM project composed of multiple related runs of SDGVM
# calls setup_SDGVM.bs which sets up each individual run 

# Arguments:
# $1 - SDGVM_USER (required) -- options: ORNL_APW, UR_PCM
# $2 - SDGVM_PROJECT name (required) -- directory relative to SDGVM_PDIR, houses a collection of runs (i.e. a project)
# $3 - SDGVM_RUNTYPE (required) -- use a predefined 'runtype' 
# $4 - SDGVM_SITESCORES (required) -- use a predefined iset of sites, resolution, and cores  
# $5 - SUBPROJECT name (optional) -- a label for a subgroup of simulations within a SDGVM_PROJECT 

SDGVM_USER="$1"
SDGVM_PROJECT="$2"
SDGVM_RUNTYPE="$3"
if [ ! -z $4 ]; then SDGVM_SITESCORES="$4"; else SDGVM_SITESCORES='CRUJRA_1deg_32cores'; fi
if [ ! -z $5 ]; then SUBPROJECT="_$5"; else SUBPROJECT=''; fi



# institute and user tag to customise simulation to user space and machine
#=================================================================================#
echo ""
echo "Project: ${SDGVM_PROJECT}"
echo "User: ${SDGVM_USER}"

if [ $SDGVM_USER == 'ORNL_APW' ]; then

  # SDGVM directory - source code, run directories, input data are all subdirs of SDGVM_HOME
  SDGVM_HOME=~/models/SDGVM
  # relative to SDGVM_HOME
  SDGVM_PROJECTS_DIR="/run/"
  SDGVM_DATA="/input_data/"
  SDGVM_MOD="/src/sdgvm/"
  # cluster scheduling variables
  #SDGVM_BATCHPROC=pbs
  #BATCHPROCCOM="qsub submit.pbs"
  SDGVM_BATCHPROC="sbatch"
  SDGVM_BATCHPROCCOM="sbatch submit.sbatch"
  SDGVM_USER_EMAIL="walkerap@ornl.gov"
  SDGVM_USER_ACCOUNT="ccsi"
  SDGVM_USER_QUEUE=""
  SDGVM_USER_PARTITION="batch"

elif [ $SDGVM_USER == 'UR_PCM' ]; then

  # SDGVM directory - source code, run directories, input data are all subdirs of SDGVM_HOME
  SDGVM_HOME="/group_workspaces/jasmin2/nexcs/pmcguire"
  # relative to SDGVM_HOME
  SDGVM_PROJECTS_DIR="/sdgvmR/"
  SDGVM_DATA="/sdgvmD/data/"
  SDGVM_MOD="/TRENDYv8/sdgvm/"
  # cluster scheduling variables
  SDGVM_BATCHPROC="bsub"
  SDGVM_BATCHPROCCOM="bsub < submit.bsub"
  SDGVM_USER_EMAIL=""
  SDGVM_USER_ACCOUNT=""
  SDGVM_USER_QUEUE="par-multi"
  SDGVM_USER_PARTITION=""

else
  echo ""
  echo "No institute and username tag: ${SDGVM_USER}"
  echo "pick one of: ORNL_APW, UR_PCM;"
  echo " or define your own"
  echo "SDGVM project setup ABORTED."
  stop
fi



# Define runtype variables
#=================================================================================#
if [ $SDGVM_RUNTYPE == 'TRENDYv7' ]; then

  # For TRENDYv7
  # - and later TRENDY iterations
  MAIN_SIMS=( S0v7 S1v7 S2v7 S3v7 S4v7 S8v7 )
  
  # Spinup directory 
  SDGVM_SPIN='spin_accelv7'

  # directory where template simulations are to be copied from, relative to model source code 
  SDGVM_CPRUN=/blank_runs/global_mp


elif [ $SDGVM_RUNTYPE == 'scratch' ]; then

  #SIMS=( NC_zen0_beers C_zen0_beers C_zen_beers C_zen0_beersC C_zen_beersC NC_zen0_LP C_zen0_LP C_zen_LP  )
  #SIMS=( Walker_N_ModA Walker_N_ModA_Tacc Kattge_ModA Kattge_ModA_Tacc  )
  #SIMS=( Constant Constant_ModA Constant_ModA_Tacc LUNA LUNA_ModA LUNA_ModA_Tacc  )
  #SIMS=( spin_accel S0 S1 S2 S3  )
  #SIMS=( tpu0 tpu1 tpu2 tpu3  )
  #SIMS=( spin_accelv7 S0v7 S1v7 S2v7 S3v7 S4v7  )
  #SIMS=( spin_accelv8 spin_shortv8 S0v8 S2p1v8 S2p1_2017_v8 S2p2v8 S2p3v8 )
  #SIMS=( spin_accelv7 S0v7 S1v7 S3v7 spin_accelv7_npslim S0v7_npslim S1v7_npslim S3v7_npslim spin_accelv7_bamort S0v7_bamort S1v7_bamort S3v7_bamort )
  #SIMS=( spin_accelv8 spin_shortv8 S0v8 S2p1v8 S2p1_2017_v8 S2p2v8 S2p3v8 )
  MAIN_SIMS=( run ) 

  # Spinup directory 
  SDGVM_SPIN='spin'

  # directory where template simulations are to be copied from, relative to model source code 
  SDGVM_CPRUN=/blank_runs/


else
  echo ""
  echo "No runtype: ${SDGVM_RUNTYPE}"
  echo "pick one of: " 
  echo " or define your own"
  echo "SDGVM project setup ABORTED."
  stop
fi

# print input vars 
echo ""
echo "Runtype: ${SDGVM_RUNTYPE}"
echo "Spin run: ${SDGVM_SPIN}"
echo "Main runs: ${MAIN_SIMS[*]}"
echo "Copy directory: ${SDGVM_CPRUN}"
echo "Sites file: sites_${SDGVM_SITESCORES}.bs"
#cp ../blank_runs/sites/sites_${SDGVM_SITESCORES}.bs $SDGVM_PDIR/$SDGVM_PROJECT/sites.bs
#sed -i "s@#HOME#@$SDGVM_HOME@" $SDGVM_PDIR/$SDGVM_PROJECT/sites.bs
#sed -i "s@#DATA#@$SDGVM_DATA@" $SDGVM_PDIR/$SDGVM_PROJECT/sites.bs




# create project and run directories and scripts
#=================================================================================#

# setup project directories
# relative to SDGVM_HOME, where all SDGVM simulations live
SDGVM_PDIR=${SDGVM_HOME}${SDGVM_PROJECTS_DIR}
mkdir -p $SDGVM_PDIR/$SDGVM_PROJECT
mkdir -p $SDGVM_PDIR/$SDGVM_PROJECT/tools
mkdir -p $SDGVM_PDIR/$SDGVM_PROJECT/tools/logs


# setup project tools
cp ./project_tools/* $SDGVM_PDIR/$SDGVM_PROJECT/tools
sed -i "s@#PROJECT#@$SDGVM_PROJECT@"                $SDGVM_PDIR/$SDGVM_PROJECT/tools/*bs
sed -i "s@#PROJDIR#@${SDGVM_PDIR}${SDGVM_PROJECT}@" $SDGVM_PDIR/$SDGVM_PROJECT/tools/*bs


# export variables
export SDGVM_USER
export SDGVM_HOME 
export SDGVM_PROJECT
export SDGVM_DATA 
export SDGVM_MOD 
export SDGVM_PDIR
export SDGVM_BATCHPROC
export SDGVM_BATCHPROCCOM
export SDGVM_SITESCORES 
export SDGVM_SPIN 
#export SDGVM_RUN 
export SDGVM_CPRUN 
export SDGVM_USER_EMAIL
export SDGVM_USER_ACCOUNT
export SDGVM_USER_QUEUE
export SDGVM_USER_PARTITION


# set up runs within project
SIMS=( $SDGVM_SPIN ${MAIN_SIMS[@]} )
for s in ${SIMS[*]};do
 echo "" 
 echo $s
 ./setup_SDGVM.bs $s 
done


# could add code here to allow for the situation where there are more than one spin per project
# var called SPIN2, if then reconfigure a few things and then run the above sims loop that calls setup_SDGVM 
# would need to alter the run script setup, adding all spins to one scripts, all main runs to the next



# setup project/subproject spin script
cp run_project_template.bs  $SDGVM_PDIR/$SDGVM_PROJECT/run_spin_${SDGVM_PROJECT}${SUBPROJECT}.bs
sed -i "s@#S#@${SDGVM_SPIN[*]}@"  $SDGVM_PDIR/$SDGVM_PROJECT/run_spin_${SDGVM_PROJECT}${SUBPROJECT}.bs
sed -i "s@#BATCHPROCCOM#@${SDGVM_BATCHPROCCOM}@"  $SDGVM_PDIR/$SDGVM_PROJECT/run_spin_${SDGVM_PROJECT}${SUBPROJECT}.bs


# setup project/subproject run script
cp run_project_template.bs  $SDGVM_PDIR/$SDGVM_PROJECT/run_${SDGVM_PROJECT}${SUBPROJECT}.bs
sed -i "s@#S#@${MAIN_SIMS[*]}@"  $SDGVM_PDIR/$SDGVM_PROJECT/run_${SDGVM_PROJECT}${SUBPROJECT}.bs
sed -i "s@#BATCHPROCCOM#@${SDGVM_BATCHPROCCOM}@"  $SDGVM_PDIR/$SDGVM_PROJECT/run_${SDGVM_PROJECT}${SUBPROJECT}.bs



### END ###
