#!/bin/bash

# This script is designed to copy a template SDGVM directory into an actual run directory
# script can be run by the user to create a single SDGVM run directory or, more commonly, called from the script 'setup_SDGVM_project.bs' to set up multiple runs within a project
# the script takes the model project directory (pre-existing) as first argument and run directory (will be created) as second argument
# the script renames the directories specified in the run and submit scripts
# once a run is setup the only file that needs editing is the input file (input*.dat)

# Arguments:
# $1 - HOME directory (required)
# $2 - project name (required)
# $3 - run name (required)

# directories 
# relative to root
HOME=$1
# relative to HOME
PROJECTS_DIR=/run/
DATA=/input_data
MOD=/src/sdgvm
# relative to MOD
CPRUN=/blank_runs/global_mp_1deg
# relative to PROJECTS_DIR
PROJECT=$2
# relative to PROJECT
RUN=$3

# copy blank run from:
CPDIR=$HOME$MOD$CPRUN
# to:
RUNDIR=$HOME$PROJECTS_DIR$PROJECT/$RUN/

# set up run directories
mkdir $RUNDIR
mkdir $RUNDIR/logs

# copy template files
cd $CPDIR
cp *param* $RUNDIR
cp *.bs    $RUNDIR
cp *.pbs   $RUNDIR

# select and copy template input file
DEFTIN=input_global.dat
SPECIN=`ls input* | grep $RUN`
if [ ! -z $SPECIN ]; then 
 INPUT=$SPECIN
else 
 INPUT=$DEFTIN 
fi
echo "Input file: " $INPUT
cp $INPUT $RUNDIR

# modify run files
sed -i "s@#RUNDIR#@$RUNDIR@"   ${RUNDIR}submit*.pbs
sed -i "s@#PROJECT#@$PROJECT@" ${RUNDIR}submit*.pbs
sed -i "s@#SIM#@$RUN@"         ${RUNDIR}submit*.pbs

sed -i "s@#DATA#@$DATA@"       ${RUNDIR}$INPUT
sed -i "s@#HOME#@$HOME@"       ${RUNDIR}$INPUT

sed -i "s@#HOME#@$HOME@"       ${RUNDIR}run_SDGVM.bs
sed -i "s@#MOD#@$MOD@"         ${RUNDIR}run_SDGVM.bs
sed -i "s@#DATA#@$DATA@"       ${RUNDIR}run_SDGVM.bs
sed -i "s@#INPUT#@$INPUT@"     ${RUNDIR}run_SDGVM.bs

sed -i "s@#HOME#@$HOME@"                        ${RUNDIR}run_postprocessing.bs
sed -i "s@#MOD#@$MOD@"                          ${RUNDIR}run_postprocessing.bs
sed -i "s@#DIR#@$HOME$PROJECT_DIR@"             ${RUNDIR}run_postprocessing.bs
sed -i "s@#PDIR#@$HOME$PROJECTS_DIR$PROJECT@"   ${RUNDIR}run_postprocessing.bs
sed -i "s@#SIM#@$RUN@"                          ${RUNDIR}run_postprocessing.bs


 
