#!/bin/bash

# This script is designed to copy a template SDGVM directory into an actual run directory
# script can be run by the user to create a single SDGVM run directory or, more commonly, called from the script 'setup_SDGVM_project.bs' to set up multiple runs within a project
# the script takes the model project directory (pre-existing) as first argument and run directory (will be created) as second argument
# the script renames the directories specified in the run and submit scripts
# once a run is setup the only file that needs editing is the input file (input*.dat)

# Arguments:
# $1 - SDGVMUSER (required) - options: ORNL_APW, UR_PCM
# $2 - HOME directory (required)
# $3 - project name (required)
# $4 - run name (required)

# directory from which to copy template runs 
# relative to MOD
#For TRENDY2018
CPRUN=/blank_runs/global_mp_1deg
#For TRENDY2019
#CPRUN=/blank_runs/global_mp_30min

# institute and user tag to customise simulation to user space and machine
SDGVMUSER=$1

# directories 
# relative to root
HOME=$2

if [ $SDGVMUSER == 'ORNL_APW' ]; then
  # relative to HOME
  PROJECTS_DIR=/run/
  DATA=/input_data
  MOD=/src/sdgvm
  # cluster queuing variables
  BATCHPROC=pbs

elif [ $SDGVMUSER == 'UR_PCM' ]; then
  # relative to HOME
  PROJECTS_DIR=/sdgvmR/
  DATA=/sdgvmD/data
  # For Drought2018
  #MOD=/Drought2018/sdgvm
  # For TRENDY2019
  MOD=/TRENDYv8/sdgvm
  # cluster queuing variables
  BATCHPROC=bsub
fi

# relative to PROJECTS_DIR
PROJECT=$3
# relative to PROJECT
RUN=$4

# copy blank run from:
CPDIR=$HOME$MOD$CPRUN
# to:
RUNDIR=$HOME$PROJECTS_DIR$PROJECT/$RUN/

# set up run directories
mkdir $RUNDIR
mkdir $RUNDIR/logs

# copy template files
cd $CPDIR
cp *param*        $RUNDIR
cp *.${BATCHPROC} $RUNDIR
cp clean.bs       $RUNDIR
cp run_postprocessing.bs $RUNDIR

# select and copy template input file
DEFTIN=input_global.dat
SPECIN=`ls input* | grep $RUN`
if [ ! -z $SPECIN ]; then 
 INPUT=$SPECIN
else 
 INPUT=$DEFTIN 
fi
echo "Input file: " $INPUT
cp $INPUT $RUNDIR

# select and copy template run file
DEFTRUN=run_SDGVM.bs
RUNF=$DEFTRUN 
SPECRUN=`echo $PROJECT | grep TRENDY`
if [ ! -z $SPECRUN ]; then RUNF=run_SDGVM_TRENDYv8.bs; fi
echo "Run file: " $RUNF
cp $RUNF ${RUNDIR}$DEFTRUN

# modify run files
sed -i "s@#RUNDIR#@$RUNDIR@"   ${RUNDIR}submit*.${BATCHPROC}
sed -i "s@#PROJECT#@$PROJECT@" ${RUNDIR}submit*.${BATCHPROC}
sed -i "s@#SIM#@$RUN@"         ${RUNDIR}submit*.${BATCHPROC}

sed -i "s@#DATA#@$DATA@"       ${RUNDIR}$INPUT
sed -i "s@#HOME#@$HOME@"       ${RUNDIR}$INPUT

sed -i "s@#HOME#@$HOME@"       ${RUNDIR}run_SDGVM.bs
sed -i "s@#MOD#@$MOD@"         ${RUNDIR}run_SDGVM.bs
sed -i "s@#DATA#@$DATA@"       ${RUNDIR}run_SDGVM.bs
sed -i "s@#INPUT#@$INPUT@"     ${RUNDIR}run_SDGVM.bs

sed -i "s@#HOME#@$HOME@"                        ${RUNDIR}run_postprocessing.bs
sed -i "s@#MOD#@$MOD@"                          ${RUNDIR}run_postprocessing.bs
sed -i "s@#DIR#@$HOME$PROJECT_DIR@"             ${RUNDIR}run_postprocessing.bs
sed -i "s@#PDIR#@$HOME$PROJECTS_DIR$PROJECT@"   ${RUNDIR}run_postprocessing.bs
sed -i "s@#SIM#@$RUN@"                          ${RUNDIR}run_postprocessing.bs
sed -i "s@#SDGVMUSER#@$SDGVMUSER@"              ${RUNDIR}run_postprocessing.bs



### END ### 
