#!/bin/bash

# script to run SDGVM in parallel on 30 cores 
# designed to be run from within it's own directory

#HOME=#HOME#
MODEL=#HOME##MOD#
SITES=#HOME##DATA#/sites/global_1deg.dat
INPUT=#INPUT#
OUTPUT=output

SITE_INDEX=( 0 450 950 1355 1730 2050 2360 2675 2990 3305 3620 4000 4490 5115 5740 6350 6780 7230 7730 8300 8825 9425 10000 10520 11040 11520 12150 12845 13490 14200 15417 )


# start script

# clear output directories
rm -r ./$OUTPUT
rm -r ./src

# copy source code and compiled model run file
mkdir ./$OUTPUT
mkdir ./src
cp $MODEL/*.f    ./src
cp $MODEL/sdgvm0 ./src

# run loop 
((e=${#SITE_INDEX[*]} - 1 ))

for s in `seq 1 $e` ;do
((s1=$s - 1))
((s2=${SITE_INDEX[$s1]} + 1))

mkdir ./$OUTPUT/grid$s

echo "./src/sdgvm0 $INPUT ./$OUTPUT/grid$s  $SITES $s2 ${SITE_INDEX[$s]} > ./$OUTPUT/g${s}out.txt &"
./src/sdgvm0 $INPUT ./$OUTPUT/grid$s  $SITES $s2 ${SITE_INDEX[$s]} > ./$OUTPUT/g${s}out.txt &

done

wait
