#!/bin/bash

# script to run SDGVM according to the sites, resolution, and cores specified in sites.bs 
# designed to be run from within the directory of a specific, single run

MODEL=/work/scratch-pw2/pmcguire/TRENDYv12/sdgvm
INPUT=input_global_S3.dat

SPINDIR='../spin_accel/output'
OUTPUT=output


# start script
# clear output directories
rm -r ./$OUTPUT
rm -r ./src


# copy source code and compiled model run file
mkdir ./$OUTPUT
mkdir ./src
cp $MODEL/*.f    ./src
cp $MODEL/sdgvm0 ./src


# sites variables
SDGVM_SITES=/work/scratch-pw2/pmcguire/TRENDYv12/db/sites/global_1deg_CRUJRA2023.dat
SDGVM_N_SITES=( 1980 625 620 610 615 515 515 515 500 510 575 575 560 430 500 500 520 525 550 575 530 630 540 540 455 445 490 510 400 400 550 511 )


# run loop 
s4=0
((e=${#SDGVM_N_SITES[*]}))
for s in `seq 1 $e` ;do
 ((s1=$s - 1))
 ((s3=1 + $s4))
 ((s4=$s4 + ${SDGVM_N_SITES[$s1]}))

 mkdir ./$OUTPUT/grid$s
 echo "./src/sdgvm0 $INPUT $SPINDIR/grid$s ./$OUTPUT/grid$s  $SDGVM_SITES $s3 $s4 > ./$OUTPUT/g${s}out.txt &"
       ./src/sdgvm0 $INPUT $SPINDIR/grid$s ./$OUTPUT/grid$s  $SDGVM_SITES $s3 $s4 > ./$OUTPUT/g${s}out.txt &

done

wait
